### ISSUE TITLE
Impossible to connect Tableau and Kobo

### ISSUE THREAD

**Issue by Dabertch** [iahmedani/kobo-wdc#8]
Hi, 

It seems there is an issue with kobo custom installation. 

I've seen on kobo forum nobody can access to their own server. 
All is fine with the kobo and kobo humanitarian.

API URL is: http://kf.mydomain.org/api/v2    Right ? If yes, there is an issue. 

Maybe kobo is updated and the WDC doesn't fit with Kobo toolbox now ?  

Thank you in advance for your answer. :)

Here is the error after trying to connect to my own kobo server:

Code d'erreur :82BE0673
Uncaught TypeError: data.forEach is not a function   stack:TypeError: data.forEach is not a function
    at Object.<anonymous> (http://kf.mydomain.org:3000/:220:18)
    at u (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:27457)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:28202)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:77651)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:79907)
    
    
    
    EDIT: It's ok ! The API URL is: kc.mydomain.com/api/v1
    I used with kf and that's why it didn't work. Sorry

**Comment by iahmedani** [comment]
Thanks for highliting, I will release an update soon.
